### PR TITLE
chore: move to travis

### PR DESCRIPTION
**Pull request by jacobheun**

### CODE REVIEW

**Comment by jacobheun** [comment]
@hugomrdias have you see this windows error? https://travis-ci.com/ipfs/js-ipfs-repo/jobs/177507079

I think ipfs-repo had issues with it in the past, but we haven't had any recent issues with it on jenkins.

**Comment by jacobheun** [comment]
Looks like this was previously fixed with a git config change https://github.com/ipfs/js-ipfs-repo/pull/153#issuecomment-346320309

**Comment by hugomrdias** [comment]
@jacobheun this is ready to be merged

**Comment by jacobheun** [comment]
@hugomrdias any idea why PR is failing but branch is passing? I tried re-running the PR build with cleared cache but Windows is still failing. Perhaps the PR commit being tested is messing with the line endings?

**Comment by hugomrdias** [comment]
its normal because the PR run is done on the merge commit and master doesn't have the gitattributes yep. 
after we merge this PR, all future PRs will have both pipelines green.

**Pull request merged**
