### PR TITLE
Introducing not found error for config values

### PR DESCRIPTION
**Pull request by AuHau**

### CODE REVIEW

**Comment by AuHau** [comment]
I have now realized that earlier I created issue #197 that propose the usage of `interface-datastore.errors.notFound` instead of this custom error.

@jacobheun what is your take on this?

**Comment by jacobheun** [comment]
@AuHau they should probably be separate. While they both have the same error code at the moment, the missing config key is not a database error. There's no guarantee the database code won't change in the future, so keeping them separate feels like a safer way to avoid issues down the road.

The `err-code` module is already being used in other places in ipfs-repo, is there any particular reason you're using error classes instead? If not it would probably be good to use the former.

**Comment by AuHau** [comment]
Sounds good! 

Well, it is a style of errors proposed in https://github.com/ipfs/js-ipfs/pull/1746 that I silently highly prefer 😅 and I hope is the future in js-ipfs land. Should I refactor it nevertheless?

**Comment by jacobheun** [comment]
My only real hesitation with including them is that we have 2 ways errors are being created now. I know there is another PR open that adds another code. Would you be up for submitting another PR to replace the rest of the err-code usage?

**Comment by AuHau** [comment]
Sure! I will happily do that. It should not be even breaking change as the `code` properties will stay the same. I will make it happen tomorrow.

**Pull request merged**
