### PR TITLE
chore: update datastore-level

### PR DESCRIPTION
**Pull request by alanshaw**
So we can get the benefits of https://github.com/ipfs/js-datastore-level/pull/15

### CODE REVIEW

**Comment by alanshaw** [comment]
Good point, I'll open a PR now...

**Comment by alanshaw** [comment]
https://github.com/ipfs/js-ipfs/pull/2026 looking good so far (just passed on linux)

**Comment by alanshaw** [comment]
@jacobheun it looks all good 🚢 🙏

**Comment by jacobheun** [comment]
v0.26.5 is on the webs!

**Pull request merged**
