### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
Currently this repository is failing on jenkins with 
```
Uncaught OpenError: IO error: c:\jenkins\workspace\IPFS_js-ipfs-repo_PR-153-GUNUWVWGXGOB3KKWNXV3RHGXDIAP7QRQCZS2QYQWYXCUFAQYJ6XQ\test\test-repo-for-1511171442216\datastore/MANIFEST-000052
: The filename, directory name, or volume label syntax is incorrect.
```

Error can be seen here: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-repo/detail/PR-153/2/pipeline

Doesn't seem to fail on AppVeyor so somewhere, something is different to make this fail on Jenkins and also hosted Windows VMs on EC2 and MacStadium vSphere cluster.

### CODE REVIEW

**Comment by richardschneider** [comment]
Well it looks the `ncp` has not finished or failed without an error.  This is a basic file copy (recursive)!

Here's the code https://github.com/ipfs/js-ipfs-repo/blob/27553a3d51ef5b2c98a21efb67e5fc12c4a8deb1/test/node.js#L46

**Comment by VictorBjelkholm** [comment]
@richardschneider In my mind, there is still a path issue somewhere as the file it's trying to open is this one:

```
c:\jenkins\workspace\IPFS_js-ipfs-repo_PR-153-GUNUWVWGXGOB3KKWNXV3RHGXDIAP7QRQCZS2QYQWYXCUFAQYJ6XQ\test\test-repo-for-1511171442216\datastore/MANIFEST-000052
```

It ends with `/datastore\MANIFEST-000052` which seems wrong (mixing forward and back-slashes). How did you come to the conclusion that `ncp` is the culprint? Checked the readme (https://www.npmjs.com/package/ncp) and seems errors should be logged to stdout and/or `./ncp-debug.log` but neither contains any output related to ncp.

**Comment by VictorBjelkholm** [comment]
btw, `ncp` doesn't seem to be maintained anymore and bunch of people are having issues with files not being copied when callback is being called, might be a good idea to migrate to a different library. Although, switching doesn't seem to fix the issue. Switched out `ncp` for `recursive-copy` and still hitting the same issue.

**Comment by richardschneider** [comment]
@VictorBjelkholm Windows is forgiving, it will allow both forward and back slashes in a path!

I think its `ncp` because the 'before-hook` only does 2 things; copy files and then open the store.

**Comment by richardschneider** [comment]
Comments on the path `C:\Windows\TEMP\test-repo-for-1511176584426\datastore/MANIFEST-000052
`
- `\windows\temp` is interesting. Normally TMP is somewhere in user's path.  Who are we logged-in as? What version of windows is running?
- `151117` is the current date (ddmmyy).  Why is date so far in the past?

**Comment by VictorBjelkholm** [comment]
> \windows\temp is interesting. Normally TMP is somewhere in user's path. Who are we logged-in as? What version of windows is running?

Administrator

> 151117 is the current date (ddmmyy). Why is date so far in the past?

No idea, computer is reporting date as `11/20/2017` which seems correct. `(new Date()).toISOString()` in a node repl also reports `2017-11-20T11:50:08.869Z`

**Comment by VictorBjelkholm** [comment]
@richardschneider tried creating a new user `Victor` with default permissions (for Windows Server 2016) and getting `The filename, directory name, or volume label syntax is incorrect.po-for-1511179358576\datastore/MANIFEST-000052` instead now

**Comment by richardschneider** [comment]
From the last run, which lists the files in the temp repo, it now appears that `at node_modules\levelup\lib\levelup.js:117:34` could be responsible,

**Comment by VictorBjelkholm** [comment]
Solved with `core.autocrlf input` in git config, as otherwise git will rewrite line-endings and make the `MANIFEST-000052` file corrupt. Opened new PR for CI updates: https://github.com/ipfs/js-ipfs-repo/pull/154

**Pull request closed without merging**
