### PR TITLE
fix: fix lock for node 11

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR swaps lock-me for proper-lockfile which fixes compat with node 11 and also brings others improvements https://github.com/moxystudio/node-proper-lockfile.
- better support for network file systems 
- staleness support
- better clean up for process shutdown

ref: https://github.com/ipfs/js-ipfs/issues/1700

### CODE REVIEW

**Comment by hugomrdias** [comment]
we aren't actually using it :) https://github.com/ipfs/js-ipfs-repo/blob/e028a9e4e27a417dbfc04141fb267e4f6fecee96/src/index.js#L197-L204

Do you want me to add a test to this private method ?

**Comment by jacobheun** [comment]
We should just remove `_isLocked` and the `locker.locked` functions then. No sense in having private code we're not using.

**Comment by jacobheun** [comment]
Linting needs fixed, otherwise this looks good.

**Comment by alanshaw** [comment]
@hugomrdias @jacobheun would you mind looking into this failure:

```console
  1) interface-ipfs-core over ipfs-api tests
       .key.rename
         "after all" hook:
     Error: Lock is already released
      at callback (node_modules/proper-lockfile/lib/lockfile.js:222:60)
      at Promise (node_modules/proper-lockfile/lib/adapter.js:39:9)
      at new Promise (<anonymous>)
      at args (node_modules/proper-lockfile/lib/adapter.js:30:25)
      at Object.close (node_modules/ipfs-repo/src/lock.js:25:9)
      at IpfsRepo._closeLock (node_modules/ipfs-repo/src/index.js:186:28)
      at series (node_modules/ipfs-repo/src/index.js:243:14)
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/async/internal/parallel.js:31:39
      at replenish (node_modules/async/internal/eachOfLimit.js:66:17)
      at iterateeCallback (node_modules/async/internal/eachOfLimit.js:50:17)
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/async/internal/onlyOnce.js:12:16
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/async/internal/parallel.js:36:13
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/async/internal/once.js:12:16
      at iteratorCallback (node_modules/async/eachOf.js:60:13)
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/async/internal/onlyOnce.js:12:16
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/levelup/lib/levelup.js:114:16
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/abstract-leveldown/abstract-leveldown.js:67:5
      at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1720-BOTRBRZAZU5M646NTADACC3XMRHJPUFDKJYCZI4VMLV72YC6IHHA@2/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:67:5
```

**Comment by hugomrdias** [comment]
On it

**Comment by Vishal1010101** [comment]
`apple$ orbitdb create hello feed
Error: Lock FcntlFlock of /Users/apple/orbitdb/ipfs/repo.lock failed: EINVAL, Invalid argument`
Can anyone help?

**Comment by jacobheun** [comment]
@Vishal1010101 see https://github.com/ipfs/js-ipfs/issues/1700#issuecomment-439993473. If you still encounter an issue, please open a new issue. Thanks!

**Pull request merged**
