### PR TITLE
refactor: new go-ipfs blockstore like interface

### PR DESCRIPTION
**Pull request by dignifiedquire**
@diasdavid

### CODE REVIEW

**Comment by diasdavid** [comment]
LGTM :D

**Comment by dignifiedquire** [comment]
This will need a big version bump as it's a very breaking change

**Comment by diasdavid** [comment]
`minor`, no? While pre `1.0.0`.

**Comment by dignifiedquire** [comment]
yes

**Comment by diasdavid** [comment]
wanna merge and release https://github.com/dignifiedquire/aegir/pull/11 so that I can use it here?

**Pull request merged**
