### PR TITLE
Windows interop

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
@VictorBjelkholm any idea why Circle is acting again?

**Comment by diasdavid** [comment]
@richardschneider can I get your help on taking this one to the finish line?

**Comment by diasdavid** [comment]
image

Appveyor and Travis are good. Circle is acting (need to figure out why), seems that we have repo interop!

**Comment by VictorBjelkholm** [comment]
Did some testing with this for the new CI setup, and got this error:

image

Was running from commit `9b8c3ba3544281ca84f611e3eecd08fce3e9f3dd`

**Comment by richardschneider** [comment]
@VictorBjelkholm created issue #150

**Pull request merged**
